name: Run Twitter Bot

on:
  workflow_dispatch:  # allows manual runs
  schedule:
    - cron: '0 12 * * 1-5'  # Runs at 12:00 UTC (which is 1PM UK time during BST) on Monday–Friday

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # <- job will automatically stop after 20 minutes

    concurrency:
      group: twitter-bot
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          python3 TwitterBot/bot.py
